services:
  - type: web
    name: focaloid-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /tmp/sentence_transformers

